### ISSUE TITLE
Work? Undetect?

### ISSUE THREAD

**Issue by ken1x1337** [TrezorTop/python-recoil-reducer#2]
Hi, I would like to try, tell me it is not detected at the moment?

**Comment by trezorsix** [comment]
Yes, you can do it. It's not reading or writing game memory, just using the tool that Windows provides, and since it's not prohibited, there are no issues.

**Comment by ken1x1337** [comment]
> Yes, you can do it. It's not reading or writing game memory, just using the tool that Windows provides, and since it's not prohibited, there are no issues.

Fine.
I got an error when "pip install -r requirements.txt" ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python312\Lib\importlib \__init__.py", line 90, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap >", line 1360, in _find_and_load File "<frozen importlib._bootstrap>" , line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 995, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "C:\Users\byk0sya\AppData\Local\Temp\pip-build-env-mliercqh\overlay\Lib\site-packages\setuptools\__init__.py", line 10, in <module> import distutils.core ModuleNotFoundError: No module named 'distutils' And before that there is still a lot of red, when trying to "pip install distutils" It throws ERROR: Could not find a version that satisfies the requirement distutils (from versions: none ) ERROR: No matching distribution found for distutils

**Comment by ken1x1337** [comment]
I deleted my 3.12 version.
Installed 3.10 and everything worked. But when building, and then when opening mine.exe, the command line opens and closes. I think something is wrong here.

**Comment by ken1x1337** [comment]
At the same time, everything works in PyCharm. I was even able to add a picture of a weapon and a profile.

I added the rest of the weapons that were missing. But I customized everything for myself. I have 50 mouse sensitivity in the sight. If necessary, I can drop it)

**Comment by TrezorTop** [comment]
You can download a compiled version of the software from the releases page, along with a full guide on how to install and use it.

**Comment by TrezorTop** [comment]
https://github.com/TrezorTop/r6s-recoil-reducer/releases/tag/v1.0.0

**Comment by ken1x1337** [comment]
ok, thanks, everything worked)
